### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by RohDong** [fangchangma/self-supervised-depth-completion#28]
'Namespace' object has no attribute 'data_folder'
i want to test only.
please give me about...

**Comment by fangchangma** [comment]
Please provide more details.

**Comment by gautamjain1009** [comment]
I have the same issue! everything is working fine but when i run main.py with the pretrained model argument  i got this similar error like down below. 

![error_sp](https://user-images.githubusercontent.com/37597326/65899617-633be980-e3b4-11e9-8a7d-8804d536f4b6.png)


I have the same folder structure as described by you in readme file.

**Comment by fangchangma** [comment]
@gautamjain1009 Thanks for the screenshot. It turns out that the problem was due to a version difference in the code and the previously saved results. I just pushed a minor update, and it should fix the issue. Let me know if it works for you now.

**Comment by gautamjain1009** [comment]
Thank you for your reply. @fangchangma 
That error is gone but still not working properly,

![Screenshot from 2019-09-30 20-13-38](https://user-images.githubusercontent.com/37597326/65904461-cfbbe600-e3be-11e9-9145-30109fa89ea3.png)


under kitti_depth in the data folder, i am using the "train" and "val" which i got from-" Download projected raw LiDaR scans data set (2 GB) " at KITTI depth completion benchmark. 

The argument is not able to find anything in the data, i have rechecked the structure and the path again.

**Comment by fangchangma** [comment]
By default we use the `../data/kitti_depth/val_selection_cropped` folder for validation. This is the "[manually selected validation and test data sets (5 GB)](http://www.cvlibs.net/download.php?file=data_depth_selection.zip)" on the KITTI website. 

I am not entirely sure if the current version of the code still supports loading the uncropped `../data/kitti_depth/val` folder, but feel free to give it a shot by adding `--val full` to your command.

**Comment by gautamjain1009** [comment]
I tried adding  "--val  full" while executing the main.py but still it gives the same issue, what should i do, to make it work.

**Comment by fangchangma** [comment]
It seems that the data structure of KITTI Depth has changed recently. I will update my code accordingly. Please stay tuned.

**Comment by fangchangma** [comment]
Just updated the code and the README for the latest file structure.
